# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlWhatif < Formula
  desc "Kubernetes cost and performance what-if simulator"
  homepage "https://github.com/tochemey/kubewise"
  version "0.1.0-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tochemey/kubewise/releases/download/v0.1.0-beta.1/kubectl-whatif_0.1.0-beta.1_darwin_amd64.tar.gz"
      sha256 "bc044ad6e8b958fe3382f1f8c1b1963e956e44eb84db702fae8d751a315bf1a1"

      define_method(:install) do
        bin.install "kubectl-whatif"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tochemey/kubewise/releases/download/v0.1.0-beta.1/kubectl-whatif_0.1.0-beta.1_darwin_arm64.tar.gz"
      sha256 "09501284b94d460dbc9ecd7d8608a91ea51a78df235489789d80717602fe3598"

      define_method(:install) do
        bin.install "kubectl-whatif"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tochemey/kubewise/releases/download/v0.1.0-beta.1/kubectl-whatif_0.1.0-beta.1_linux_amd64.tar.gz"
      sha256 "95291601fd1ed1d0770f88258548f5b7199adb108ef6684ed07c7d2487e1fac4"
      define_method(:install) do
        bin.install "kubectl-whatif"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tochemey/kubewise/releases/download/v0.1.0-beta.1/kubectl-whatif_0.1.0-beta.1_linux_arm64.tar.gz"
      sha256 "68f6b20f3701b9ab35573c468f0da94abb57e991884839bdb5a2ea593ea9e6c2"
      define_method(:install) do
        bin.install "kubectl-whatif"
      end
    end
  end
end
