# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlWhatif < Formula
  desc "Kubernetes cost and performance what-if simulator"
  homepage "https://github.com/tochemey/kubewise"
  version "0.1.0-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tochemey/kubewise/releases/download/v0.1.0-alpha/kubectl-whatif_0.1.0-alpha_darwin_amd64.tar.gz"
      sha256 "5514989a9f35ba094f991c28891ee9d935842628a2567f3004ab0d45ab19ace1"

      define_method(:install) do
        bin.install "kubectl-whatif"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tochemey/kubewise/releases/download/v0.1.0-alpha/kubectl-whatif_0.1.0-alpha_darwin_arm64.tar.gz"
      sha256 "48acfda437fa05c4f5f59fbd37e1fef750a70abf2cc4737fa153f9ac37b35c43"

      define_method(:install) do
        bin.install "kubectl-whatif"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tochemey/kubewise/releases/download/v0.1.0-alpha/kubectl-whatif_0.1.0-alpha_linux_amd64.tar.gz"
      sha256 "955e4d82e741dfa61e48f22443c7a501fe65f5d469331a2c8e7849460093b543"
      define_method(:install) do
        bin.install "kubectl-whatif"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tochemey/kubewise/releases/download/v0.1.0-alpha/kubectl-whatif_0.1.0-alpha_linux_arm64.tar.gz"
      sha256 "b61fe5c1488990e504ca08ec9c48fe96ba870ec17b79b64458b0b718070a6bd0"
      define_method(:install) do
        bin.install "kubectl-whatif"
      end
    end
  end
end
